### ISSUE TITLE
Create Basic Enemies

### ISSUE THREAD

**Issue by sensible-heart** [WibblyWobblyGames/ProjectFQDA#1]
Create basic enemies that can be interacted with by the player character.

Links to Subtasks:
- [x] #2 Enemies Damage the Player Character
- [x] #3 Player Damages Enemies
- [x] #4 Player Death

**Comment by megsum** [comment]
The player health has been implemented, all we need to do now is when the enemy attacks, have the player take damage. I have set it to 100 health for now. The player has a global variable called health_player that can be increased or decreased when necessary!

**Comment by adamjford** [comment]
Thanks Megan! Starting on the rest of the enemy-related deliverables now. :100:
