### ISSUE TITLE
Finalize Princess Sprite 

### ISSUE THREAD

**Issue by OmegaSheep** [WibblyWobblyGames/ProjectFQDA#10]
Specifically the following:
- Colour and outfit
- Facing issue. Does she need to face in all 4 directions? Or strictly left right? (We could move eyes up and down if moving up or down).
- Weapon / Spells? How will they be held? Does her stance support this? 
- What did the original Princess look like? (Need to draw the Kawaii eyes etc)

**Comment by krwarren** [comment]
I think we talked about this in Slack, I'll rework the initial sprite with the new palette and facings
