### ISSUE TITLE
Player Animation Jumping

### ISSUE THREAD

**Issue by LeahGabrielle** [WibblyWobblyGames/ProjectFQDA#21]
I noticed that the player animation is jumping when you switch from left to right. Is that just on my end for some reason?

**Comment by megsum** [comment]
Yeah, that was the reason I had the origin in the center because the animation flips on the origin, so if the origin is on the top left or whatever, when we mirror the animation it is going to jump.

**Comment by adamjford** [comment]
Sounds like a bug!

**Comment by megsum** [comment]
It isn't. It is just the way that game maker handles mirroring. If we really wanted to we could make a new sprite for every animation (left and right running, left and right attack and left and right idle), and then it would work, but as it is now it just flips the right animation on the origin, which won't work if the origin is the top left corner.

**Comment by adamjford** [comment]
Ah, looks like we should probably revert the decentering then.
