### ISSUE TITLE
Centralize pushing code into a script

### ISSUE THREAD

**Issue by adamjford** [WibblyWobblyGames/ProjectFQDA#74]
Things that push the player:
- Mimic
- Robot
- Space Wizard

It would be nice if these all called one single script to do so, which respects `obj_collision_parent`.

**Comment by LeahGabrielle** [comment]
pretty sure robots do this too, so it's probably a good idea to add it to them all if that works

**Comment by adamjford** [comment]
That's why I put it on the list. ;)

**Comment by megsum** [comment]
Sounds good. I will try to get it done by tonight.

**Comment by megsum** [comment]
Is it okay if I just add this code to my #73 branch?

**Comment by adamjford** [comment]
Whatever works best for you.

**Comment by megsum** [comment]
I didn't get it into a script yet so I am going to keep this open for now because I will work on it later this week.

**Comment by adamjford** [comment]
You planning on doing this for our submission tomorrow?

**Comment by megsum** [comment]
I didn't realize it was due tomorrow, so no :( It can be closed

**Comment by adamjford** [comment]
No worries! What we have works.
