### ISSUE TITLE
Create Mecha Wizard Sprite

### ISSUE THREAD

**Issue by sensible-heart** [WibblyWobblyGames/ProjectFQDA#9]
Create a a 32-bit mecha wizard sprite, either 2x1 or 2x2.

**Comment by sensible-heart** [comment]
This is complete right?

**Comment by OmegaSheep** [comment]
Essentially yes. I need to animate it, and might end up changing it. As far as the weekly goal is concerned I say it is complete though.

**Comment by sensible-heart** [comment]
Okey doke I will close this item now and create a new work item concerning animation.
